
print("---------------------------------------------------------------------------------------------\n")
print("For Multifunction Calculator Enter 1\n\n")
print("For Simple Calculator Enter 2\n\n")
a = int(input())


if  a==1:
    print("Enter the First Number For Calculation.\n")
    a = int(input())
    print("Enter the Second Number For Calculation\n")
    b = int(input())
    print("------------------------------Output------------------------------------------------------")
    print("Sum of  Numbers \n")
    print(a + b )
    print("Substraction of Numbers  \n")
    print( a - b)
    print("Mutiplication of Numbers \n")
    print(a * b )
    print("Division of Numbers \n")
    print(a / b )
    print("-------------------------------------------------------------------------------------------")
if a==2:
    print("Enter the First Number For Sum.\n")
    a = int(input())
    print("Enter the Second Number For Sum\n")
    b = int(input())
    print("Enter the First Number For Substraction\n")
    c = int(input())
    print("Enter the Second Number For Substraction\n")
    d = int(input())
    print("Enter the First Number For Multiplication\n")
    e = int(input())
    print("Enter the Second Number For Multiplication\n")
    f = int(input())
    print("Enter the First Number For Division\n")
    g = int(input())
    print("Enter the Second Number For Division\n")
    h = int(input())
    print("------------------------------------Output--------------------------------------------------")
    print("Result of Addition\n")
    print(a+b)
    print("Result of Substraction\n")
    print(c -d)
    print("Result of Multiplication\n")
    print(e * f)
    print("Result of Division\n")
    print(g / h)
    print("---------------------------------------------------------------------------------------------")
    
    
